import { TodoCreateInput, UserCreateInput } from '@prisma/client'

export const TODO_FIXTURES: TodoCreateInput[] = [
  { id: 'id_01', text: 'veritatis molestias qui', isCompleted: false },
  { id: 'id_02', text: 'occaecati a dolor', isCompleted: false },
  { id: 'id_03', text: 'ut enim quia', isCompleted: false },
  { id: 'id_04', text: 'ipsam ipsam corrupti', isCompleted: true },
  { id: 'id_05', text: 'voluptatem sint ipsam', isCompleted: true },
  { id: 'id_06', text: 'ut sunt consequuntur', isCompleted: true },
  { id: 'id_07', text: 'accusamus aut labore', isCompleted: false },
  { id: 'id_08', text: 'et quo quia', isCompleted: true },
  { id: 'id_09', text: 'accusantium a excepturi', isCompleted: true },
  { id: 'id_10', text: 'deserunt rerum occaecati', isCompleted: true },
  { id: 'id_11', text: 'unde et quasi', isCompleted: false },
  { id: 'id_12', text: 'et autem sapiente', isCompleted: false },
  { id: 'id_13', text: 'deleniti fuga et', isCompleted: false },
  { id: 'id_14', text: 'ea molestiae similique', isCompleted: true },
  { id: 'id_15', text: 'doloribus ea aut', isCompleted: false },
  { id: 'id_16', text: 'ut molestias veniam', isCompleted: true },
  { id: 'id_17', text: 'a placeat aperiam', isCompleted: true },
  { id: 'id_18', text: 'quos rerum aut', isCompleted: true },
  { id: 'id_19', text: 'ullam a voluptatem', isCompleted: false },
  { id: 'id_20', text: 'dolorum deserunt quis', isCompleted: true },
]

export const USER_FIXTURES: UserCreateInput[] = [
  { id: 1, email: 'user1@email.com', username: 'user1' },
  { id: 2, email: 'user2@email.com', username: 'user2', isAdmin: true },
  { id: 3, email: 'user3@email.com', username: 'user2', isAdmin: false },
  { id: 4, email: 'user4@email.com', username: 'user4' },
  { id: 5, email: 'user5@email.com', username: 'user5' },
  { id: 6, email: 'user6@email.com', username: 'user6' },
  { id: 7, email: 'user7@email.com', username: 'user7' },
  { id: 8, email: 'user8@email.com', username: 'user8' },
  { id: 9, email: 'user9@email.com', username: 'user9' },
  { id: 10, email: 'user10@email.com', username: 'user10' },
  { id: 11, email: 'user11@email.com', username: 'user11' },
  { id: 12, email: 'user12@email.com', username: 'user12' },
  { id: 13, email: 'user13@email.com', username: 'user13' },
  { id: 14, email: 'user14@email.com', username: 'user14' },
  { id: 15, email: 'user15@email.com', username: 'user15' },
  { id: 16, email: 'user16@email.com', username: 'user16' },
  { id: 17, email: 'user17@email.com', username: 'user17' },
  { id: 18, email: 'user18@email.com', username: 'user18' },
  { id: 19, email: 'user19@email.com', username: 'user19' },
  { id: 20, email: 'user20@email.com', username: 'user20' },
]
