export const TODO_FIXTURES = [
  { id: 'id_01', text: 'veritatis molestias qui', isCompleted: false },
  { id: 'id_02', text: 'occaecati a dolor', isCompleted: false },
  { id: 'id_03', text: 'ut enim quia', isCompleted: false },
  { id: 'id_04', text: 'ipsam ipsam corrupti', isCompleted: true },
  { id: 'id_05', text: 'voluptatem sint ipsam', isCompleted: true },
  { id: 'id_06', text: 'ut sunt consequuntur', isCompleted: true },
  { id: 'id_07', text: 'accusamus aut labore', isCompleted: false },
  { id: 'id_08', text: 'et quo quia', isCompleted: true },
  { id: 'id_09', text: 'accusantium a excepturi', isCompleted: true },
  { id: 'id_10', text: 'deserunt rerum occaecati', isCompleted: true },
  { id: 'id_11', text: 'unde et quasi', isCompleted: false },
  { id: 'id_12', text: 'et autem sapiente', isCompleted: false },
  { id: 'id_13', text: 'deleniti fuga et', isCompleted: false },
  { id: 'id_14', text: 'ea molestiae similique', isCompleted: true },
  { id: 'id_15', text: 'doloribus ea aut', isCompleted: false },
  { id: 'id_16', text: 'ut molestias veniam', isCompleted: true },
  { id: 'id_17', text: 'a placeat aperiam', isCompleted: true },
  { id: 'id_18', text: 'quos rerum aut', isCompleted: true },
  { id: 'id_19', text: 'ullam a voluptatem', isCompleted: false },
  { id: 'id_20', text: 'dolorum deserunt quis', isCompleted: true },
]
